[features]
seeds = false

[programs.devnet]
contract = "DNgWmEiQBVkuCBrRhbacDAA2Wi3mkkWyofuKquQg2Zur"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/harish/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "node tests/contract.js"

[test]
startup_wait = 100000
